spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/beauty_scheduler
    username: beauty_user
    password: beauty_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: ''
    password: ''
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
